services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.20
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,gds.*'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import

  app:
    image: python:3.11-slim
    command: ["/bin/bash","/work/app/start.sh"]
    working_dir: /work/app
    volumes:
      - ./app:/work/app:cached
      - ./scripts:/work/scripts:ro   # ‚Üê add this
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://app:secret@postgres:5432/shop
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - postgres
      - neo4j

volumes:
  postgres_data:
